pipeline:
  processors:
    - label: kafka_message_parse
      mapping: |
        root.request_id = this.request_id.or("unknown")  # Extract user_id or default to "unknown"
        root.request_name = this.request_name
        root.requested_by = this.requested_by
        root.status = "GL_SYNC_INITIATED"
output:
  broker:
    outputs:
      - label: consolelog
        stdout:
          codec: lines
      - label: insert_into_zio_db
        sql_insert:
          driver: postgres
          dsn: postgres://postgres:postgres@localhost:5432/zio?sslmode=disable
          table: nfcu.zio_gl_sync_request_master
          columns: ["request_id", "request_name", "requested_by", "status"]
          args_mapping: |
            root = [
              this.request_id,
              this.request_name,
              this.requested_by,
              this.status
            ]
          options: []
          max_in_flight: 64
          init_files: []
          conn_max_idle: 2
          batching:
            count: 0
            byte_size: 0
            period: ""
            check: ""
      - label: consolelog_again
        stdout:
          codec: lines
      - label: push_message_to_token_topic
        kafka:
          addresses:
            - localhost:19092
          tls:
            enabled: false
            skip_cert_verify: false
            enable_renegotiation: false
            root_cas: ""
            root_cas_file: ""
            client_certs: []
          sasl:
            mechanism: none
            user: ""
            password: ""
            access_token: ""
            token_cache: ""
            token_key: ""
          topic: token_master_topic
          partitioner: round_robin
          max_in_flight: 1
          batching:
            count: 1
