pipeline:
  processors:
    - label: ""
      noop:
        additionalProperties: false
        properties:
          component:
            additionalProperties: false
            properties: {}
            type: object
        type: object
